name: color_generator_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dartz: 0.10.1
  json_annotation: 4.8.1
  retrofit: 4.0.1
  dio: 5.3.2
  retrofit_generator: 7.0.8
  equatable: 2.0.5
  cupertino_icons: 1.0.2
  flutter_bloc: 8.1.3
  get_it: 7.6.4

dev_dependencies:
  json_serializable: 6.7.1
  build_runner: 2.4.6
  solid_lints: 0.0.19
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

 
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 
